### ISSUE TITLE
Registering a user using an invitation for which the role assigned is deleted produces an error

### ISSUE THREAD

**Issue by baakal** [tech-acs/chimera-starter-kit#31]
Steps to produce this error:

1. create a new role
2. invite a user to the dashboard and assign the new role to the user
3. before the user accepts the invitation, delete the role
4. the user will not be able to register because the role is not found

Expected:
 The user should be able to register with no roles assigned

**Comment by amestsantim** [comment]
Fixed in commit: c83f36f470619330a429c21702de63b5f94df1bc
